### ISSUE TITLE
Using Tools configured in OpenWebUI

### ISSUE THREAD

**Issue by proud-nerd** [TheRealPSV/ha-openwebui-conversation#37]
### Checklist

- [x] I have filled out the template to the best of my ability.
- [x] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [x] This issue is not a duplicate feature request of [previous feature requests](https://github.com/TheRealPSV/ha-openwebui-conversation/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I'm not sure if this is a configuration issue on my side, but I can't get the agent from this integration to use the tools I configured in Open WebUI. Is that even supported?

### Describe the solution you'd like

I would like the agent in Home Assistant to use any tools I configured in OpenWebUI.

### Describe alternatives you've considered

I don't see any alternative, since there is no option that let's me use tool integrations from within Home Assistant like https://www.home-assistant.io/integrations/mcp/.

### Additional context

.

**Comment by TheRealPSV** [comment]
I'm not currently using any Tools myself, so I'd need to look into this more.

Are you using the [AutoTool Filter](https://openwebui.com/f/hub/autotool_filter)? That may be what you want.

**Comment by proud-nerd** [comment]
I'll look into that, I remember trying that but it didn't look like it was doing much.

Currently I activated the tools I want to be active by default in the settings for the model:

![Image](https://github.com/user-attachments/assets/19951871-fe61-47e2-b47e-ea979a1e628b)

![Image](https://github.com/user-attachments/assets/a442e197-f7ca-4ee6-b494-e27be5b981d7)

Here is my `docker-compose.yml` for some mcp tools, just to save you some time if you want to try this yourself.
```
  mcp-server:
    container_name: mcp-server
    image: ghcr.io/open-webui/mcpo:main
    restart: unless-stopped
    ports:
      - 9005:8000
    networks:
      - ollama
    depends_on:
      - openwebui
    environment:
      TZ: Europe/Berlin
    volumes:
      - ./mcpo/config.json:/app/config.json:rw
    command: ["--api-key", "${MCPO_API_KEY}", "--config", "/app/config.json"]
```

and the config.json:
```                                          
{
  "mcpServers": {
    "fetch": {
      "command": "uvx",
      "args": [
        "mcp-server-fetch"
      ]
    },
    "sequential-thinking": {
      "command": "npx",
      "args": [
        "-y",
        "@modelcontextprotocol/server-sequential-thinking"
      ]
    },
    "brave-search": {
      "command": "npx",
      "args": [
        "-y",
        "brave-search-mcp"
      ],
      "env": {
        "BRAVE_API_KEY": ${BRAVE_API_KEY}
      }
    }
  }
}
```
